version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env.local:/app/.env.local:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s